### ISSUE TITLE
May I know if you share image also?

### ISSUE THREAD

**Issue by CindyTing** [google-research-datasets/adversarial-nibbler#1]
Hello authors,

Thanks very much for your sharing! 
I have a few questions below:
1. I'm very interested in this work, may I know if you will share the image data also? or if only prompts are available in the future?
2. May I know which seven image classifier you used in Table 7, and which five text classifier you used in Table 6?

Thanks very much for your help! Looking forward to your reply!

Sincerely,
Cindy

**Comment by CindyTing** [comment]
And also may I request access to the round2 and round3 reports? Now I can't open it because I don't have access.

**Comment by Alicia-Parrish** [comment]
You can find the reports for rounds 2 and 3 in the readme under [reports](https://github.com/google-research-datasets/adversarial-nibbler?tab=readme-ov-file#reports).

We do not share images by default, as there is potential harm in releasing the images. The prompt set can be used to generate images with any model, so that the safety of the system can be tested. However, if you have a specific research need for the images that were generated during the Nibbler competition, please complete the form [here](https://forms.gle/4Lfr2eSxGmFjNFxC9) and we will review requests on a case-by-case basis. 

The tables you reference use an ensemble of proprietary classifiers, and we cannot release specific data about them beyond what is already published in the paper. For this reason, we also include results from open source classifiers in the appendix, and will rely on the open source classifiers in future work.
